# Generated by Django 5.1.3 on 2025-06-03 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nansen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceiot',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='missions', to=settings.AUTH_USER_MODEL),
        ),
    ]
