# Generated by Django 5.1.3 on 2025-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nansen', '0002_alter_deviceiot_is_available_alter_mission_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
